name: chainsync

on:
  schedule:
    # Run on Monday at 1am UTC
    - cron: '0 1 * * 1'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  mainnet:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - run: |
          make
      - run: |
          ./gouroboros -network mainnet -address relays-new.cardano-mainnet.iohk.io:3001 -ntn chain-sync -bulk

  preview:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - run: |
          make
      - run: |
          ./gouroboros -network preview -address preprod-node.world.dev.cardano.org:30002 -ntn chain-sync -bulk

  preprod:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - run: |
          make
      - run: |
          ./gouroboros -network preprod -address preprod-node.world.dev.cardano.org:30000 -ntn chain-sync -bulk
